

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 43028

[20:12:01] Extension host agent started.
[20:12:02] [127.0.0.1][1532acb7][ManagementConnection] New connection established.
[20:12:02] [127.0.0.1][bbf5c574][ExtensionHostConnection] New connection established.
[20:12:02] [127.0.0.1][bbf5c574][ExtensionHostConnection] <1619> Launched Extension Host Process.
[20:38:56] [127.0.0.1][1532acb7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:38:57] [127.0.0.1][bbf5c574][ExtensionHostConnection] <1619> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[20:38:57] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:39:00] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:39:00] Cancelling previous shutdown timeout
[20:39:00] [127.0.0.1][60d25442][ManagementConnection] New connection established.
[20:39:00] [127.0.0.1][89b02f6a][ExtensionHostConnection] New connection established.
[20:39:00] [127.0.0.1][89b02f6a][ExtensionHostConnection] <3068> Launched Extension Host Process.
[20:39:23] [127.0.0.1][60d25442][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:39:24] [127.0.0.1][89b02f6a][ExtensionHostConnection] <3068> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[20:39:24] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[20:39:24] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:39:27] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:39:27] Cancelling previous shutdown timeout
[20:39:27] [127.0.0.1][9d4cc28f][ManagementConnection] New connection established.
[20:39:27] [127.0.0.1][d2914b2d][ExtensionHostConnection] New connection established.
[20:39:27] [127.0.0.1][d2914b2d][ExtensionHostConnection] <3180> Launched Extension Host Process.
New EH opened, aborting shutdown
[20:44:27] New EH opened, aborting shutdown
[20:44:32] [127.0.0.1][9d4cc28f][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:44:33] [127.0.0.1][d2914b2d][ExtensionHostConnection] <3180> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[20:44:33] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:44:36] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:44:36] Cancelling previous shutdown timeout
[20:44:36] [127.0.0.1][395d95de][ManagementConnection] New connection established.
[20:44:36] [127.0.0.1][b25d6a65][ExtensionHostConnection] New connection established.
[20:44:36] [127.0.0.1][b25d6a65][ExtensionHostConnection] <3761> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "17"
stack trace: Error: Could not find pty with id "17",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "17",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "17"
stack trace: Error: Could not find pty with id "17",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "17",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
[20:44:41] [127.0.0.1][395d95de][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:44:42] [127.0.0.1][b25d6a65][ExtensionHostConnection] <3761> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[20:44:42] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[20:44:42] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:44:45] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:44:45] Cancelling previous shutdown timeout
[20:44:45] [127.0.0.1][c02e09f1][ManagementConnection] New connection established.
[20:44:46] [127.0.0.1][495039e0][ExtensionHostConnection] New connection established.
[20:44:46] [127.0.0.1][495039e0][ExtensionHostConnection] <3865> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "21"
stack trace: Error: Could not find pty with id "21",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "21",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "21"
stack trace: Error: Could not find pty with id "21",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "21",    at M._throwIfNoPty (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/tli2/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
New EH opened, aborting shutdown
[20:49:45] New EH opened, aborting shutdown
[21:21:32] [127.0.0.1][c02e09f1][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[21:21:33] [127.0.0.1][495039e0][ExtensionHostConnection] <3865> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[21:21:33] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[21:26:33] Last EH closed, shutting down
